;;;; runtime/commands.lisp --- The command registry.
;;;;
;;;; A command is a named, documented, argument-taking function that a key can
;;;; be bound to and a human can invoke by name.  It is Emacs's M-x, and it
;;;; exists for the same reason: *a keybinding should name a thing, not be the
;;;; thing.*
;;;;
;;;; That matters more here than it looks.  README's P1 — where a fork is
;;;; situational rather than principled, both options ship and configuration
;;;; picks the default — guarantees a large command count.  P1's own stated
;;;; cost is that it is only affordable if the verbs are genuinely orthogonal
;;;; (verb × direction × scope, composed) rather than enumerated.  A registry
;;;; of named commands taking arguments is what makes composition possible:
;;;; `move' takes a direction and a scope, and the keymap is generated by
;;;; crossing them, rather than being forty hand-written entries.

(in-package #:latticewm/runtime)

(defclass command ()
  ((name :initarg :name :reader command-name)
   (function :initarg :function :accessor command-function)
   (lambda-list :initarg :lambda-list :initform '() :reader command-lambda-list)
   (documentation :initarg :documentation :initform nil
                  :reader command-documentation)
   (props :initform '() :accessor c:props))
  (:documentation "A named operation, invocable by key or by name."))

(defmethod print-object ((command command) stream)
  (print-unreadable-object (command stream :type t :identity nil)
    (format stream "~a~@[ ~s~]" (command-name command)
            (command-lambda-list command))))

(defvar *commands* (make-hash-table :test #'equal)
  "Downcased name string -> COMMAND.")

(defmacro defcommand (name lambda-list &body body)
  "Define a command.

    (defcommand focus (direction)
      \"Move the cursor one pane DIRECTION.\"
      (move-cursor (current-policy) *world* direction))

NAME is a symbol, or a list of a symbol and the name to register it under:

    (defcommand (close-window \"close\") () ...)

The two forms exist because a handful of good command names — `close' is the
one that bites — are Common Lisp symbols we may not redefine, and renaming the
*user-visible* command to work around a package lock would be letting an
implementation detail reach the keyboard.

The first form of BODY should be a docstring, and the build gate says so if it
is not: a command without one cannot be found by anybody who does not already
know it exists.

The command is also an ordinary function, so Lisp code calls it directly
without going through the registry."
  (let* ((symbol (if (consp name) (first name) name))
         (string (string-downcase (if (consp name) (second name) (string symbol))))
         (documentation (when (and (stringp (first body)) (rest body))
                          (first body)))
         (forms (if documentation (rest body) body)))
    `(progn
       (defun ,symbol ,lambda-list
         ,@(when documentation (list documentation))
         ,@forms)
       (setf (gethash ,string *commands*)
             (make-instance 'command
                            :name ,string
                            :function #',symbol
                            :lambda-list ',lambda-list
                            :documentation ,documentation))
       ',symbol)))

(defun find-command (name)
  "The command called NAME, or NIL.  NAME may be a string or a symbol."
  (gethash (string-downcase (string name)) *commands*))

(defun all-commands ()
  "Every command, sorted by name."
  (let ((out '()))
    (maphash (lambda (name command) (declare (ignore name)) (push command out))
             *commands*)
    (sort out #'string< :key #'command-name)))

(defun run-command (name &rest arguments)
  "Look NAME up and run it with ARGUMENTS.

An unknown command logs and returns NIL rather than signalling: commands come
from key bindings and from configuration files, where a typo should produce a
message and a working window manager rather than a broken session."
  (let ((command (find-command name)))
    (cond
      ((null command) (logmsg :warn "no such command: ~a" name) nil)
      (t (guarded (format nil "command ~a" name)
           (apply (command-function command) arguments))))))

(defun undocumented-commands ()
  "Every command with no docstring.  Build gate 2 covers these too."
  (remove-if #'command-documentation (all-commands)))
