;;;; runtime/config.lisp --- Defaults, the default keymap, and the user's file.
;;;;
;;;; PLAN.org promotes the configuration file from a detail to a primary
;;;; deliverable: "under the extensibility ruling this is a primary
;;;; deliverable, not a detail.  Every P1 fork must appear here as a tier-0
;;;; value."
;;;;
;;;; The default keymap below is generated by crossing verbs with directions
;;;; rather than being written out.  That is not cleverness for its own sake —
;;;; it is P1's affordability condition made visible.  If the bindings had to
;;;; be enumerated, four verbs times four directions times two scopes would be
;;;; thirty-two hand-written lines that can each be individually wrong.

(in-package #:latticewm/runtime)

;;; --------------------------------------------------- the program defaults

(p:define-option *terminal* "foot"
  "The terminal emulator the `terminal' command runs.")

(p:define-option *editor* "emacs"
  "The editor the `editor' command runs.")

(p:define-option *browser* "firefox"
  "The web browser the `browser' command runs.")

(p:define-option *file-manager* "thunar"
  "The file manager the `files' command runs.")

(p:define-option *modifier* :super
  "The modifier every default binding uses.

:SUPER is the only one that does not collide with something an application
already wants.")

(p:define-option *cursor-theme* nil
  "The xcursor theme name, or NIL to leave the compositor's default alone.")

(p:define-option *cursor-size* 24
  "The xcursor size in logical pixels.")

;;; ------------------------------------------------------- the default keymap

(defun modifier-string (&rest extra)
  "The default modifier plus EXTRA, as a key-spec prefix."
  (format nil "~{~a+~}" (cons (string-downcase *modifier*)
                              (mapcar #'string-downcase extra))))

(defparameter +direction-keys+
  '((:left "h" "Left") (:down "j" "Down") (:up "k" "Up") (:right "l" "Right"))
  "Each direction with the keys that mean it.

Both vi letters and the arrow keys are bound, always, and that is deliberate
rather than indecisive: the arrows are what somebody uses on their first day
and the letters are what they use on their hundredth, and making them choose
up front is a bad trade for four extra lines of table.")

(defun install-default-keymap (&optional (keymap *keymap*))
  "Bind the shipped keymap.  Every binding is generated, not enumerated.

Called before the user's configuration file, so that anything the file binds
wins."
  (let ((mod (modifier-string))
        (shift (modifier-string :shift))
        (ctrl (modifier-string :ctrl))
        (alt (modifier-string :alt)))
    ;; --- the verb x direction grid.  Four lines, sixteen bindings. ---------
    (loop for (direction . keys) in +direction-keys+
          do (dolist (key keys)
               (define-key keymap (format nil "~a~a" mod key)
                 (list "focus" direction))
               (define-key keymap (format nil "~a~a" shift key)
                 (list "move" direction))
               (define-key keymap (format nil "~a~a" ctrl key)
                 (list "resize" direction))
               (define-key keymap (format nil "~a~a" alt key)
                 (list "swap" direction))))
    ;; --- panes ------------------------------------------------------------
    (define-key keymap (format nil "~areturn" mod) '("terminal"))
    (define-key keymap (format nil "~ad" mod) '("split" :horizontal))
    (define-key keymap (format nil "~as" mod) '("split" :vertical))
    (define-key keymap (format nil "~aq" mod) '("close"))
    (define-key keymap (format nil "~aq" shift) '("clear"))
    (define-key keymap (format nil "~atab" mod) '("focus-next"))
    (define-key keymap (format nil "~atab" shift) '("focus-previous"))
    (define-key keymap (format nil "~ae" mod) '("equalize"))
    (define-key keymap (format nil "~ae" shift) '("equalize-all"))
    ;; --- disposition ------------------------------------------------------
    (define-key keymap (format nil "~aspace" mod) '("toggle-float"))
    (define-key keymap (format nil "~af" mod) '("toggle-fullscreen"))
    (define-key keymap (format nil "~am" mod) '("minimize"))
    (define-key keymap (format nil "~am" shift) '("restore-last"))
    (define-key keymap (format nil "~aw" mod) '("tab"))
    (define-key keymap (format nil "~aw" shift) '("untab"))
    (define-key keymap (format nil "~abracketright" mod) '("tab-next"))
    (define-key keymap (format nil "~abracketleft" mod) '("tab-previous"))
    ;; --- workspaces.  Generated, and the send-to variant comes free. -------
    (loop for index from 0 below 10
          for key = (format nil "~d" (mod (1+ index) 10))
          do (define-key keymap (format nil "~a~a" mod key)
               (list "workspace" index))
             (define-key keymap (format nil "~a~a" shift key)
               (list "send-to-workspace" index)))
    (define-key keymap (format nil "~an" mod) '("new-workspace"))
    (define-key keymap (format nil "~apagedown" mod) '("next-workspace"))
    (define-key keymap (format nil "~apageup" mod) '("previous-workspace"))
    ;; --- launching --------------------------------------------------------
    (define-key keymap (format nil "~ab" mod) '("browser"))
    (define-key keymap (format nil "~ao" mod) '("editor"))
    ;; --- the window manager itself ---------------------------------------
    (define-key keymap (format nil "~ac" shift) '("reload-config"))
    (define-key keymap (format nil "~ar" shift) '("restart-wm"))
    (define-key keymap (format nil "~aescape" shift) '("quit"))
    keymap))

;;; ------------------------------------------------------- the user's file

(defun config-directory ()
  "Where the user's configuration lives: $XDG_CONFIG_HOME/latticewm/."
  (merge-pathnames
   "latticewm/"
   (or (uiop:getenv-absolute-directory "XDG_CONFIG_HOME")
       (merge-pathnames ".config/" (user-homedir-pathname)))))

(defun config-file ()
  "The user's init.lisp."
  (merge-pathnames "init.lisp" (config-directory)))

(defun load-config (&optional (path (config-file)))
  "Load the user's configuration, if there is one.

It is read in the LATTICEWM/USER package, which inherits the model, the policy
surface and the runtime wholesale — so a configuration file writes

    (defmethod should-float-p ((p policy) (win window))
      (or (call-next-method) (equal (window-app-id win) \"pavucontrol\")))

with no package prefixes anywhere.

An error in the file is logged and does not stop startup.  A window manager
that refuses to run because of a typo in its configuration leaves the user
with no way to fix the typo, which is the worst possible failure for this
particular program."
  (if (probe-file path)
      (handler-case
          (let ((*package* (find-package '#:latticewm/user)))
            (load path)
            (logmsg :info "loaded ~a" path)
            t)
        (error (condition)
          (logmsg :error "error in ~a: ~a~%(continuing with defaults)"
                  path condition)
          nil))
      (progn (logmsg :info "no configuration at ~a; using defaults" path)
             nil)))

(defun write-sample-config (&optional (path (config-file)))
  "Write a commented starter configuration, if none exists yet."
  (when (probe-file path)
    (return-from write-sample-config nil))
  (ensure-directories-exist path)
  (with-open-file (out path :direction :output :if-exists :error)
    (write-string (sample-config) out))
  (logmsg :info "wrote a starter configuration to ~a" path)
  path)

(defun sample-config ()
  "The text of the starter configuration file."
  (format nil "~
;;;; ~~/.config/latticewm/init.lisp
;;;;
;;;; Plain Common Lisp, read in the LATTICEWM/USER package, which has the whole
;;;; model, the policy surface and the runtime visible without prefixes.
;;;;
;;;; Everything here takes effect at startup.  Everything here can ALSO be
;;;; evaluated into the running window manager from a REPL — connect with
;;;; M-x slime-connect to port 4005 — and takes effect immediately, with no
;;;; restart and without losing your layout.
;;;;
;;;; \"latticewm --list-options\" prints every value with its default and its
;;;; documentation.  \"latticewm --extension-surface\" prints every generic you
;;;; can specialize.

(in-package #:latticewm/user)

;;; ------------------------------------------------------------- tier 0
;;; Values.  Change these first; they cover most of what people want.

;; (setf *gaps* 6)                     ; space between panes
;; (setf *border-width* 2)
;; (setf *focused-border-color* '(0.9 0.5 0.2 1.0))
;; (setf *terminal* \"alacritty\")
;; (setf *spawn-mode* :split)          ; :split | :fill-first | :stack
;; (setf *split-axis* :longer)         ; :longer | :horizontal | :vertical
;; (setf *focus-after-close* :stay)    ; :stay | :mru | :next
;; (setf *focus-follows-mouse* t)

;;; ------------------------------------------------------------- keys
;;; A binding names a command, so redefining the command later takes effect
;;; without rebinding the key.

;; (define-key *keymap* \"Super+Return\" '(\"terminal\"))
;; (define-key *keymap* \"Super+Shift+q\" '(\"close\"))

;; A chord.  River's ensure_next_key_eaten makes submaps exit cleanly on a key
;; they do not bind, so this behaves the way it does in Emacs.
;; (let ((window-map (make-keymap :name \"window\")))
;;   (define-key window-map \"h\" '(\"focus\" :left))
;;   (define-key window-map \"l\" '(\"focus\" :right))
;;   (define-key *keymap* \"Super+w\" window-map))

;;; ------------------------------------------------------------- tier 1
;;; Behaviour.  One DEFMETHOD changes one decision.  See doc/EXTENDING.org for
;;; the full list; every one of them has a docstring you can read at a REPL
;;; with (describe 'should-float-p).

;; Float a couple of applications that get tiling wrong.
;; (defmethod should-float-p ((policy conventional-policy) (win window))
;;   (or (call-next-method)
;;       (member (window-app-id win) '(\"pavucontrol\" \"blueman-manager\")
;;               :test #'equal)))

;; Bigger gaps around lattice cells than around splits inside them.
;; (defmethod gaps ((policy conventional-policy) (container split)) 4)

;;; ------------------------------------------------------------- hooks
;;; Notice that something happened.  Use a method when you want to *change* a
;;; decision; use a hook when you only want to react.

;; (add-hook :window-opened
;;           (lambda (win) (format t \"~~&opened ~~a~~%\" (window-app-id win))))

;;; ------------------------------------------------------ the lattice
;;; The infinite 2D plane of cells, with zoom and pan.  It is a separate system
;;; and loading it is opt-in.

;; (asdf:load-system \"lattice\")
;; (lattice:enable)
"))
