;;;; policy/keymap.lisp --- The shipped keymap, generated rather than typed.
;;;;
;;;; MOVED OUT OF RUNTIME/CONFIG.LISP, and the argument for moving it is the
;;;; one that file already made for something smaller.  *TERMINAL*, *EDITOR*,
;;;; *BROWSER*, *FILE-MANAGER* and *MODIFIER* were moved into policy/ on the
;;;; grounds that they are "the five values a person is most likely to change
;;;; on their first day" -- and INSTALL-DEFAULT-KEYMAP, ninety-seven lines of
;;;; DEFINE-KEY and the most customised object in any window manager, stayed
;;;; behind in the runtime beside the code that finds $XDG_CONFIG_HOME.
;;;;
;;;; Nothing noticed, because the gate that polices this shape polices a
;;;; filename prefix.  A reader looking for "where are the keys decided" had to
;;;; know that the answer was in the file about configuration files.
;;;;
;;;; THE BINDINGS ARE GENERATED BY CROSSING VERBS WITH DIRECTIONS rather than
;;;; being written out, and that is not cleverness for its own sake -- it is
;;;; PLAN's P1 affordability condition made visible.  Enumerated, four verbs
;;;; times four directions times two scopes would be thirty-two hand-written
;;;; lines that can each be individually wrong.

(in-package #:latticewm/policy)

;;; ------------------------------------------------------- the default keymap

(defun modifier-string (&rest extra)
  "The default modifier plus EXTRA, as a key-spec prefix."
  (format nil "~{~a+~}" (cons (string-downcase *modifier*)
                              (mapcar #'string-downcase extra))))

(defparameter +direction-keys+
  '((:left "h" "Left") (:down "j" "Down") (:up "k" "Up") (:right "l" "Right"))
  "Each direction with the keys that mean it.

Both vi letters and the arrow keys are bound, always, and that is deliberate
rather than indecisive: the arrows are what somebody uses on their first day
and the letters are what they use on their hundredth, and making them choose
up front is a bad trade for four extra lines of table.")

(defun install-default-keymap (&optional (keymap *keymap*))
  "Bind the shipped keymap.  Every binding is generated, not enumerated.

Called before the user's configuration file, so that anything the file binds
wins."
  (let ((mod (modifier-string))
        (shift (modifier-string :shift))
        (ctrl (modifier-string :ctrl))
        (alt (modifier-string :alt))
        (screen (modifier-string :ctrl :shift)))
    ;; --- the verb x direction grid.  Five lines, twenty bindings. ----------
    ;;
    ;; FOCUS-OUTPUT IS DELIBERATELY NOT HERE, and the omission is the point.
    ;; Motion crosses the screen boundary on its own now, so `Super+Right' at
    ;; the right-hand edge of the left monitor already puts you on the right
    ;; one -- see *MOTION-CROSSES-OUTPUTS*.  A chord for what a key you are
    ;; already pressing does would be a second way to say one thing, and this
    ;; file's own argument about the help submap is that a chord has to be
    ;; earned.  FOCUS-OUTPUT is still a command, reachable by name, for the
    ;; case where you are in the middle of a screen and do not want to walk.
    ;;
    ;; SEND-TO-OUTPUT has no such free version -- `move' in a direction moves
    ;; within the tree, and there is no edge for it to fall off -- so it takes
    ;; the one modifier pair the grid had left.
    (loop for (direction . keys) in +direction-keys+
          do (dolist (key keys)
               (define-key keymap (format nil "~a~a" mod key)
                 (list "focus" direction))
               (define-key keymap (format nil "~a~a" shift key)
                 (list "move" direction))
               (define-key keymap (format nil "~a~a" ctrl key)
                 (list "resize" direction))
               (define-key keymap (format nil "~a~a" alt key)
                 (list "swap" direction))
               (define-key keymap (format nil "~a~a" screen key)
                 (list "send-to-output" direction))))
    ;; --- panes ------------------------------------------------------------
    (define-key keymap (format nil "~areturn" mod) '("terminal"))
    (define-key keymap (format nil "~ad" mod) '("split" :horizontal))
    (define-key keymap (format nil "~as" mod) '("split" :vertical))
    (define-key keymap (format nil "~aq" mod) '("close"))
    (define-key keymap (format nil "~aq" shift) '("clear"))
    (define-key keymap (format nil "~atab" mod) '("focus-next"))
    (define-key keymap (format nil "~atab" shift) '("focus-previous"))
    (define-key keymap (format nil "~ae" mod) '("equalize"))
    (define-key keymap (format nil "~ae" shift) '("equalize-all"))
    ;; --- disposition ------------------------------------------------------
    (define-key keymap (format nil "~aspace" mod) '("toggle-float"))
    (define-key keymap (format nil "~aspace" shift) '("focus-float"))
    (define-key keymap (format nil "~agrave" mod) '("focus-float"))
    (define-key keymap (format nil "~af" mod) '("toggle-fullscreen"))
    (define-key keymap (format nil "~am" mod) '("minimize"))
    (define-key keymap (format nil "~am" shift) '("restore-last"))
    (define-key keymap (format nil "~aw" mod) '("tab"))
    (define-key keymap (format nil "~aw" shift) '("untab"))
    (define-key keymap (format nil "~abracketright" mod) '("tab-next"))
    (define-key keymap (format nil "~abracketleft" mod) '("tab-previous"))
    ;; --- workspaces.  Generated, and the send-to variant comes free. -------
    ;; Workspaces are one-based, so the key and the number on it agree.  Super+1
    ;; is workspace 1; Super+0 is workspace 10, which is the convention every
    ;; tiling window manager uses and nobody has ever had to be told.
    (loop for number from 1 to 10
          for key = (format nil "~d" (mod number 10))
          do (define-key keymap (format nil "~a~a" mod key)
               (list "workspace" number))
             (define-key keymap (format nil "~a~a" shift key)
               (list "send-to-workspace" number)))
    (define-key keymap (format nil "~an" mod) '("new-workspace"))
    (define-key keymap (format nil "~apagedown" mod) '("next-workspace"))
    (define-key keymap (format nil "~apageup" mod) '("previous-workspace"))
    ;; --- undoing ----------------------------------------------------------
    ;; The keys every program has used for this for thirty years.  Undo is a
    ;; *layout* undo — it puts the arrangement back and cannot un-quit an
    ;; application — and saying so is the command's own docstring's job.
    (define-key keymap (format nil "~az" mod) '("undo"))
    (define-key keymap (format nil "~az" shift) '("redo"))
    ;; --- named scratchpads and tags ---------------------------------------
    ;; Both prompt for a name, which is the point: one key reaches any number
    ;; of them, rather than one key per scratchpad as i3 needs.
    (define-key keymap (format nil "~aminus" mod) '("scratchpad-toggle"))
    (define-key keymap (format nil "~aminus" shift) '("scratchpad-put"))
    (define-key keymap (format nil "~at" mod) '("tag-window"))
    (define-key keymap (format nil "~at" shift) '("jump-to-tag"))
    ;; --- launching --------------------------------------------------------
    (define-key keymap (format nil "~ab" mod) '("browser"))
    (define-key keymap (format nil "~ao" mod) '("editor"))
    ;; --- the window manager itself ---------------------------------------
    (define-key keymap (format nil "~aslash" mod) '("help"))
    (define-key keymap (format nil "~ax" mod) '("run-command-by-name"))
    (define-key keymap (format nil "~asemicolon" mod) '("eval-expression"))
    (define-key keymap (format nil "~aperiod" mod) '("repeat"))
    (define-key keymap (format nil "~ap" mod) '("goto-named-cell"))
    (define-key keymap (format nil "~an" shift) '("name-this"))
    ;; --- asking, as a submap.  Emacs's C-h, and the one chord we ship. ----
    ;; It earns the chord: these are the five questions somebody has about a
    ;; system they are learning, they are asked rarely enough that a two-key
    ;; sequence is no burden, and pressing the prefix alone lists them in the
    ;; echo area — so the submap is its own documentation.
    (let ((help-map (make-keymap :name "help")))
      (define-key help-map "b" '("help"))
      (define-key help-map "k" '("describe-key"))
      (define-key help-map "c" '("describe-command"))
      (define-key help-map "f" '("describe-command"))
      (define-key help-map "a" '("apropos-command"))
      (define-key help-map "o" '("describe-option"))
      (define-key help-map "s" '("set-option"))
      (define-key help-map "u" '("undo-history"))
      (define-key help-map "t" '("list-tags"))
      (define-key help-map "p" '("list-scratchpads"))
      (define-key keymap (format nil "~aquestion" shift) help-map))
    (define-key keymap (format nil "~ac" shift) '("reload-config"))
    (define-key keymap (format nil "~ar" shift) '("restart-wm"))
    (define-key keymap (format nil "~aescape" shift) '("quit"))
    keymap))
