#!/usr/bin/env python3
"""Convert a PSF console font into src/runtime/font-table.lisp.

Run once, by hand, when changing fonts.  The output is vendored so that the
ordinary build needs no font file and no font library:

    tools/psf-to-lisp.py $(nix-build '<nixpkgs>' -A terminus_font --no-out-link)\
        /share/consolefonts/ter-116n.psf.gz
"""
import gzip, struct, sys, os

def load(path):
    data = gzip.open(path, 'rb').read() if path.endswith('.gz') else open(path,'rb').read()
    if data[:2] == b'\x36\x04':
        charsize = data[3]
        return data[4:], 8, charsize
    if data[:4] == b'\x72\xb5\x4a\x86':
        _, hdr, _, _, charsize, h, w = struct.unpack('<IIIIIII', data[4:32])
        return data[hdr:], w, h
    raise SystemExit("not a PSF file: " + path)

def main():
    path = sys.argv[1] if len(sys.argv) > 1 else \
        "/nix/store/hqhz5vkxdj4h2ryvcib8l9gb5dp97hmf-terminus-font-4.49.1/share/consolefonts/ter-116n.psf.gz"
    glyphs, width, height = load(path)
    stride = (width + 7) // 8
    assert stride == 1, "only 8-pixel-wide fonts are supported"
    rows = []
    for code in range(32, 127):
        off = code * height * stride
        g = glyphs[off:off + height * stride]
        rows.append((code, list(g)))
    body = []
    for code, g in rows:
        ch = chr(code)
        label = {'"': 'quote', '\\': 'backslash', ';': 'semicolon'}.get(ch, ch)
        body.append("    " + " ".join("#x%02x" % b for b in g) + "   ; %s" % label)
    out = FONT_TEMPLATE.format(
        width=width, height=height, count=len(rows),
        source=os.path.basename(path), data="\n".join(body))
    with open("src/runtime/font-table.lisp", "w") as f:
        f.write(out)
    print("wrote src/runtime/font-table.lisp: %d glyphs, %dx%d"
          % (len(rows), width, height))
    print("runtime/font.lisp is hand-written and is not touched by this script.")

FONT_TEMPLATE = r''';;;; runtime/font-table.lisp --- The glyph table.  GENERATED, WHOLLY.
;;;;
;;;; Do not edit this file.  This script writes it and nothing else, and the
;;;; four functions that used to be the tail of it -- CURRENT-FONT, GLYPH-ROW,
;;;; TEXT-WIDTH and TEXT-HEIGHT, four functions of the running program -- are in
;;;; runtime/font.lisp, which is ordinary source.  They lived inside the Python
;;;; string literal below: nothing indented them, nothing compiled them until
;;;; they had been pasted out, and editing one meant editing a string in another
;;;; language.
;;;;
;;;; Terminus {width}x{height}, imported from {source}.
;;;;
;;;; Terminus Font is copyright (c) 2020 Dimitar Toshkov Zhekov and is licensed
;;;; under the SIL Open Font License, Version 1.1.  The full licence text is in
;;;; doc/OFL-TERMINUS.txt and must travel with any copy of this file.
;;;;
;;;; Row-major: one byte per row, bit 7 leftmost.

(in-package #:latticewm/runtime)

(defparameter +font-width+ {width})
(defparameter +font-height+ {height})
(defparameter +font-first+ 32 "The first character the table covers.")

(defparameter +font+
  (make-array (* {count} {height}) :element-type (quote (unsigned-byte 8))
   :initial-contents
   (list
{data}
    ))
  "ASCII 32 to 126, {height} row bytes each.")
'''

main()
